/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Step1RouteImport } from './routes/step1'
import { Route as SessionInfoRouteImport } from './routes/session-info'
import { Route as ResearcherRouteImport } from './routes/researcher'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as IndexRouteImport } from './routes/index'

const Step1Route = Step1RouteImport.update({
  id: '/step1',
  path: '/step1',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionInfoRoute = SessionInfoRouteImport.update({
  id: '/session-info',
  path: '/session-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherRoute = ResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/researcher': typeof ResearcherRoute
  '/session-info': typeof SessionInfoRoute
  '/step1': typeof Step1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/researcher': typeof ResearcherRoute
  '/session-info': typeof SessionInfoRoute
  '/step1': typeof Step1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/researcher': typeof ResearcherRoute
  '/session-info': typeof SessionInfoRoute
  '/step1': typeof Step1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consent' | '/researcher' | '/session-info' | '/step1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consent' | '/researcher' | '/session-info' | '/step1'
  id: '__root__' | '/' | '/consent' | '/researcher' | '/session-info' | '/step1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  ResearcherRoute: typeof ResearcherRoute
  SessionInfoRoute: typeof SessionInfoRoute
  Step1Route: typeof Step1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/step1': {
      id: '/step1'
      path: '/step1'
      fullPath: '/step1'
      preLoaderRoute: typeof Step1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-info': {
      id: '/session-info'
      path: '/session-info'
      fullPath: '/session-info'
      preLoaderRoute: typeof SessionInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher': {
      id: '/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof ResearcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  ResearcherRoute: ResearcherRoute,
  SessionInfoRoute: SessionInfoRoute,
  Step1Route: Step1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
